/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:80452639-18d8-4ced-ad1f-41341d90c88c",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_QE3lHVGPr",
    "aws_user_pools_web_client_id": "44ppb2e0unmepa6hvt0ank7sl0",
    "oauth": {}
};


export default awsmobile;
